name: Cypress E2E Tests with Applitools

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        browser: [chrome, firefox]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Start application (if needed)
        run: |
          # Якщо потрібно запустити локальний сервер
          # npm start &
          # sleep 30
          echo "Using external URL: https://coffee-cart.app"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headless: true
          record: false
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          CYPRESS_BASE_URL: https://coffee-cart.app
          APPLITOOLS_BATCH_ID: ${{ github.sha }}
          APPLITOOLS_BATCH_NAME: 'GitHub Actions - ${{ github.ref_name }}'

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}-node${{ matrix.node-version }}
          path: cypress/screenshots
          retention-days: 7

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}-node${{ matrix.node-version }}
          path: cypress/videos
          retention-days: 7

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports-${{ matrix.browser }}-node${{ matrix.node-version }}
          path: cypress/reports
          retention-days: 30

  notify:
    runs-on: ubuntu-latest
    needs: [cypress-run]
    if: always()
    
    steps:
      - name: Notify on success
        if: needs.cypress-run.result == 'success' && needs.mobile-tests.result == 'success'
        run: |
          echo "✅ All tests passed successfully!"

      - name: Notify on failure
        if: needs.cypress-run.result == 'failure' || needs.mobile-tests.result == 'failure'
        run: |
          echo "❌ Some tests failed. Check the logs and Applitools dashboard."
