name: Visual Regression Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run visual regression tests
        run: |
          npm run cy:run -- --spec "cypress/e2e/**/*.cy.js" --env visual=true
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_BATCH_NAME: 'PR Visual Check - ${{ github.head_ref }}'
          APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha }}
          
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👀 Visual regression tests completed! Check [Applitools Dashboard](https://eyes.applitools.com) for results.'
            })
